// Generated by CoffeeScript 1.9.3
(function() {
  chrome.browserAction.onClicked.addListener(function(tab) {
    var url;
    url = (chrome.extension.getURL('page/index.html')) + "#/?tab=" + tab.id;
    return chrome.tabs.create({
      url: url
    });
  });

}).call(this);

//# sourceMappingURL=background.js.map
